name: Build and test

on:
  push:
    branches:
      - ae/test-windows-2025-vs2026

jobs:
  build_test_tket_windows:
    name: Build and test (tket)
    strategy:
      matrix:
        os: ['windows-2025-vs2026']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Select Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Install conan
        uses: turtlebrowser/get-conan@v1.2
      - name: Set up conan
        shell: bash
        run: |
          conan profile detect
          DEFAULT_PROFILE_PATH=`conan profile path default`
          PROFILE_PATH=./conan-profiles/${{ matrix.os }}
          diff ${DEFAULT_PROFILE_PATH} ${PROFILE_PATH} || true
          cp ${PROFILE_PATH} ${DEFAULT_PROFILE_PATH}
          conan remote add tket-libs https://quantinuumsw.jfrog.io/artifactory/api/conan/tket1-libs --index 0
      - name: normalize line endings in conanfile and src directory
        # This is necessary to ensure consistent revisions across platforms.
        # Conan's revision hash is composed of hashes of all the exported files,
        # so we must normalize the line endings in these.
        run: |
          $tket_files = Get-ChildItem "tket" -File -Recurse
          $tket_files += Get-Item "TKET_VERSION"
          $tket_c_api_files = Get-ChildItem "tket-c-api" -File -Recurse
          $tket_files += $tket_c_api_files
          foreach ($f in $tket_files) {
            $normalized_file = [IO.File]::ReadAllText($f) -replace "`r`n", "`n"
            [IO.File]::WriteAllText($f, $normalized_file)
          }
      - name: ninja ccache setup
        # This is what hendrikmuhs/ccache-action does, but for windows (theirs is buggy on windows)
        id: ninja-ccache-setup
        run: |
          choco upgrade ccache ninja
          $ccache_dir = ccache --get-config cache_dir
          echo ccache_dir=$ccache_dir >> $env:GITHUB_OUTPUT
          ccache --set-config=max_size='500M'
          ccache --set-config=compression=true
          ccache --set-config compiler_check=content
          ccache --set-config namespace=WITH_TESTS
          ccache -p
      - name: Get current time
        uses: josStorer/get-current-time@v2.1.2
        id: current_time
        with:
          format: YYYYMMDDHHmmss
      - name: ccache windows
        uses: actions/cache@v5
        with:
          path: ${{ steps.ninja-ccache-setup.outputs.ccache_dir }}
          key: tket-static-${{ matrix.os }}-${{ steps.current_time.outputs.formattedTime }}
          restore-keys: |
            tket-static-${{ matrix.os }}-
      - name: Build tket
        # On windows use build + export-pkg so build directory is consistent across runs (i.e. don't build from conan cache)
        # Necessary because setting ccache base_dir doesn't currently work on windows
        run: |
          conan build tket --user=tket --channel=stable -o boost/*:header_only=True -o with_all_tests=True -c tools.cmake.cmaketoolchain:generator=Ninja
          conan export-pkg tket --user=tket --channel=stable -o boost/*:header_only=True -o with_all_tests=True -c tools.cmake.cmaketoolchain:generator=Ninja
      - name: Build tket-c-api
        # On windows use build + export-pkg so build directory is consistent across runs (i.e. don't build from conan cache)
        # Necessary because setting ccache base_dir doesn't currently work on windows
        run: |
          conan build tket-c-api --user=tket --channel=stable -o boost/*:header_only=True -o tket/*:with_all_tests=True -c tools.cmake.cmaketoolchain:generator=Ninja
          conan export-pkg tket-c-api --user=tket --channel=stable -o boost/*:header_only=True -o tket/*:with_all_tests=True -c tools.cmake.cmaketoolchain:generator=Ninja
      - name: Upload packages
        if: github.event_name == 'push'
        run: |
          ccache --set-config namespace=WITHOUT_TESTS
          conan build tket --user=tket --channel=stable -o boost/*:header_only=True
          conan export-pkg tket --user=tket --channel=stable -o boost/*:header_only=True
          conan build tket-c-api --user=tket --channel=stable -o boost/*:header_only=True
          conan export-pkg tket-c-api --user=tket --channel=stable -o boost/*:header_only=True
          conan remote login -p ${{ secrets.JFROG_ARTIFACTORY_TOKEN_3 }} tket-libs ${{ secrets.JFROG_ARTIFACTORY_USER_3 }}
          conan upload tket/${{ needs.check_changes.outputs.tket_ver }}@tket/stable -r=tket-libs
          conan upload tket-c-api/${{ needs.check_changes.outputs.tket_ver }}@tket/stable -r=tket-libs
      - name: ccache stats
        run: |
          ccache -s  #show stats
          ccache -z  #show stats
